name: PR stats

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  track:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }

      - run: pip install --quiet matplotlib pandas requests

      - name: Collect PR data
        run: python collect_data.py

      - name: Generate chart
        run: python generate_chart.py

      - name: Commit chart
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "chore: update PR‑approval chart"
          file_pattern: "data.csv chart.png"
